   services:
     - type: web
       name: teste-rag
       env: python
       buildCommand: pip install -r requirements.txt
       startCommand: gunicorn app:app
       envVars:
         - key: PYTHON_VERSION
           value: 3.10.0
         - key: MONGODB_URI
           sync: false
         - key: OPENAI_API_KEY
           sync: false